### ISSUE TITLE
2 ip address for 1 server

### ISSUE THREAD

**Issue by titov32** [pymodbus-dev/pymodbus#2212] opened 2024-06-06 07:07 UTC
I am doing emulator device which have 2 ethernet link. How to assign second ip address for modbus server can listen 2 ip address? For example I create 2 device with addresses: 1 device: 10.1.0.1  and 10.2.0.1 and 2 device 10.1.0.2 and 10.2.0.2.

**Comment by janiversen** [comment] 2024-06-14 11:25
Closing, as this is not a bug, but pr design....however pull requests are welcome.

**Closed** 2024-06-14 11:25 UTC
