### ISSUE TITLE
Cannot get coils to read correctly

### ISSUE THREAD

**Issue by carthoris** [pymodbus-dev/pymodbus#2505] opened 2024-12-14 17:24 UTC
We are using out-of-the-box modbus simulator. We successfully were able to read registers but are having a hard time reading coils.
We initialized all the coils with a 0x1 and only get 1 coil back with a 1.

When running and stopping in debug we get 

[True, False, False, False, False, False, False, False]

instead of what we expect to be all True.

We have been playing with the client.read_coils method trying different addresses and counts to no success.

We are using a modified sample client to try to get the coils to read as follows:

#!/usr/bin/env python3
"""Pymodbus synchronous client example.

An example of a single threaded synchronous client.

usage: simple_sync_client.py

All options must be adapted in the code
The corresponding server must be started before e.g. as:
    python3 server_sync.py
"""

# --------------------------------------------------------------------------- #
# import the various client implementations
# --------------------------------------------------------------------------- #
import pymodbus.client as ModbusClient
from pymodbus import (
    FramerType,
    ModbusException,
    pymodbus_apply_logging_config,
)

def run_sync_simple_client(comm, host, port, framer=FramerType.SOCKET):
    """Run sync client."""
    # activate debugging
    pymodbus_apply_logging_config("DEBUG")

    print("get client")
    client: ModbusClient.ModbusBaseSyncClient
    if comm == "tcp":
        client = ModbusClient.ModbusTcpClient(
            host,
            port=port,
            framer=framer,
            # timeout=10,
            # retries=3,
            # source_address=("localhost", 0),
        )
    elif comm == "udp":
        client = ModbusClient.ModbusUdpClient(
            host,
            port=port,
            framer=framer,
            # timeout=10,
            # retries=3,
            # source_address=None,
        )
    elif comm == "serial":
        client = ModbusClient.ModbusSerialClient(
            port,
            framer=framer,
            # timeout=10,
            # retries=3,
            baudrate=9600,
            bytesize=8,
            parity="N",
            stopbits=1,
            # handle_local_echo=False,
        )
    else:
        print(f"Unknown client {comm} selected")
        return

    print("connect to server")
    client.connect()

    print("get and verify data")
    try:
        **rr = client.read_coils(0, count=8, slave=1)**
    except ModbusException as exc:
        print(f"Received ModbusException({exc}) from library")
        client.close()
        return
    if rr.isError():
        print(f"Received exception from device ({rr})")
        # THIS IS NOT A PYTHON EXCEPTION, but a valid modbus message
        client.close()
        return
    """
    try:
        # See all calls in client_calls.py
        rr = client.read_holding_registers(0, count=1, slave=1)
        ww = client.write_register(0, 5, slave=1)
    except ModbusException as exc:
        print(f"Received ModbusException({exc}) from library")
        client.close()
        return
    if rr.isError():
        print(f"Received exception from device ({rr})")
        # THIS IS NOT A PYTHON EXCEPTION, but a valid modbus message
        client.close()
        return
    value_int32 = client.convert_from_registers(rr.registers, data_type=client.DATATYPE.INT16)
    print(f"Got : {value_int32}")
"""
    print("close connection")
    client.close()

if __name__ == "__main__":
    #run_sync_simple_client("tcp", "GG-DELL-2024", "5020")
    run_sync_simple_client("tcp", "localhost", "5020")
    

**Here is the config.json we are using and we are using devicev.**

{
    "server_list": {
        "server": {
            "comm": "tcp",
            "host": "localhost",
            "port": 5020,
            "ignore_missing_slaves": false,
            "framer": "socket",
            "identity": {
                "VendorName": "pymodbus",
                "ProductCode": "PM",
                "VendorUrl": "https://github.com/pymodbus-dev/pymodbus/",
                "ProductName": "pymodbus Server",
                "ModelName": "pymodbus Server",
                "MajorMinorRevision": "3.1.0"
            }
        },
        "server_try_serial": {
            "comm": "serial",
            "port": "/dev/tty0",
            "stopbits": 1,
            "bytesize": 8,
            "parity": "N",
            "baudrate": 9600,
            "timeout": 3,
            "reconnect_delay": 2,
            "framer": "rtu",
            "identity": {
                "VendorName": "pymodbus",
                "ProductCode": "PM",
                "VendorUrl": "https://github.com/pymodbus-dev/pymodbus/",
                "ProductName": "pymodbus Server",
                "ModelName": "pymodbus Server",
                "MajorMinorRevision": "3.1.0"
            }
        },
        "server_try_tls": {
            "comm": "tls",
            "host": "0.0.0.0",
            "port": 5020,
            "certfile": "certificates/pymodbus.crt",
            "keyfile": "certificates/pymodbus.key",
            "ignore_missing_slaves": false,
            "framer": "tls",
            "identity": {
                "VendorName": "pymodbus",
                "ProductCode": "PM",
                "VendorUrl": "https://github.com/pymodbus-dev/pymodbus/",
                "ProductName": "pymodbus Server",
                "ModelName": "pymodbus Server",
                "MajorMinorRevision": "3.1.0"
            }
        },
        "server_test_try_udp": {
            "comm": "udp",
            "host": "0.0.0.0",
            "port": 5020,
            "ignore_missing_slaves": false,
            "framer": "socket",
            "identity": {
                "VendorName": "pymodbus",
                "ProductCode": "PM",
                "VendorUrl": "https://github.com/pymodbus-dev/pymodbus/",
                "ProductName": "pymodbus Server",
                "ModelName": "pymodbus Server",
                "MajorMinorRevision": "3.1.0"
            }
        }
    },
    "device_list": {
        "device": {
            "setup": {
                "co size": 63000,
                "di size": 63000,
                "hr size": 63000,
                "ir size": 63000,
                "shared blocks": true,
                "type exception": true,
                "defaults": {
                    "value": {
                        "bits": 0,
                        "uint16": 0,
                        "uint32": 0,
                        "float32": 0.0,
                        "string": " "
                    },
                    "action": {
                        "bits": null,
                        "uint16": "increment",
                        "uint32": "increment",
                        "float32": "increment",
                        "string": null
                    }
                }
            },
            "invalid": [
                1
            ],
            "write": [
                3
            ],
            "bits": [
                {"addr": 2, "value": 7}
            ],
            "uint16": [
                {"addr": 3, "value": 17001, "action": null},
                2100
            ],
            "uint32": [
                {"addr": [4, 5], "value": 617001, "action": null},
                [3037, 3038]
            ],
            "float32": [
                {"addr": [6, 7], "value": 404.17},
                [4100, 4101]
            ],
            "string": [
                5047,
                {"addr": [16, 20], "value": "A_B_C_D_E_"}
            ],
            "repeat": [
            ]
        },
        "device_try": {
            "setup": {
                "co size": 63000,
                "di size": 63000,
                "hr size": 63000,
                "ir size": 63000,
                "shared blocks": true,
                "type exception": true,
                "defaults": {
                    "value": {
                        "bits": 0,
                        "uint16": 0,
                        "uint32": 0,
                        "float32": 0.0,
                        "string": " "
                    },
                    "action": {
                        "bits": null,
                        "uint16": null,
                        "uint32": null,
                        "float32": null,
                        "string": null
                    }
                }
            },
            "invalid": [
                [0, 5],
                77
            ],
            "write": [
                10
            ],
            "bits": [
                10,
                1009,
                [1116, 1119],
                {"addr": 1144, "value": 1},
                {"addr": [1148,1149], "value": 32117},
                {"addr": [1208, 1306], "action": "random"}
            ],
            "uint16": [
                11,
                2027,
                [2126, 2129],
                {"addr": 2164, "value": 1},
                {"addr": [2168,2169], "value": 32117},
                {"addr": [2208, 2304], "action": "increment"},
                {"addr": 2305,
                    "value": 50,
                    "action": "increment",
                    "parameters": {"minval": 45, "maxval": 155}
                },
                {"addr": 2306,
                    "value": 50,
                    "action": "random",
                    "parameters": {"minval": 45, "maxval": 55}
                }
            ],
            "uint32": [
                [12, 13],
                [3037, 3038],
                [3136, 3139],
                {"addr": [3174, 3175], "value": 1},
                {"addr": [3188,3189], "value": 32514},
                {"addr": [3308, 3407], "action": null},
                {"addr": [3688, 3875], "value": 115, "action": "increment"},
                {"addr": [3876, 3877],
                    "value": 50000,
                    "action": "increment",
                    "parameters": {"minval": 45000, "maxval": 55000}
                },
                {"addr": [3878, 3879],
                    "value": 50000,
                    "action": "random",
                    "parameters": {"minval": 45000, "maxval": 55000}
                }
            ],
            "float32": [
                [14, 15],
                [4047, 4048],
                [4146, 4149],
                {"addr": [4184, 4185], "value": 1},
                {"addr": [4188, 4191], "value": 32514.2},
                {"addr": [4308, 4407], "action": null},
                {"addr": [4688, 4875], "value": 115.7, "action": "increment"},
                {"addr": [4876, 4877],
                    "value": 50000.0,
                    "action": "increment",
                    "parameters": {"minval": 45000.0, "maxval": 55000.0}
                },
                {"addr": [4878, 48779],
                    "value": 50000.0,
                    "action": "random",
                    "parameters": {"minval": 45000.0, "maxval": 55000.0}
                }
            ],
            "string": [
                {"addr": [16, 20], "value": "A_B_C_D_E_"},
                {"addr": [529, 544], "value": "Brand name, 32 bytes...........X"}
            ],
            "repeat": [
            ]
        },
        "devicev": {
            "setup": {
                "co size": 8,
                "di size": 8,
                "ir size": 5,
                "hr size": 5,
                "shared blocks": false,
                "type exception": true,
                "defaults": {
                    "value": {
                        "bits": 0,
                        "uint16": 0,
                        "uint32": 0,
                        "float32": 0.0,
                        "string": " "
                    },
                    "action": {
                        "bits": null,
                        "uint16": null,
                        "uint32": null,
                        "float32": null,
                        "string": null
                    }
                }
            },
            "invalid": [
            ],
            "write": [
			    [0, 7],
                [21, 25]
            ],
            "bits": [
			  {"addr": [0, 15], "value": 1}
            ],
            "uint16": [
                [16, 25]
            ],
            "uint32": [
            ],
            "float32": [
            ],
            "string": [
            ],
            "repeat": [
            ]
        }
    }
}

**Comment by janiversen** [comment] 2024-12-15 08:05
You have not defined 8 bit as true, but only 1 bit. I'm the bit section address is (if I remember correctly) for a single bit.

**Comment by janiversen** [comment] 2024-12-15 08:09
You client call looks ok, please add a debug log (as pr issue template) so we can see what the server actually sends.

**Comment by janiversen** [comment] 2024-12-15 08:10
The problem might be your addressing, coils are addressed as bits not registers, so the first 16bit are stored in register 1 etc.

**Comment by janiversen** [comment] 2024-12-15 09:47
A good idea is to reduce the json to only contain the server type and device you are actually using, otherwise it's quite pure guesswork to help.

**Comment by janiversen** [comment] 2024-12-18 17:31
Closing as this seems to be a configuration issue, and not a bug.

Feel free to correct if I am wrong.

**Closed by janiversen** 2024-12-18 17:31 UTC

**Comment by carthoris** [comment] 2024-12-24 02:50
most likely it is configuration but not sure what.

**Comment by janiversen** [comment] 2024-12-24 08:20
Looks like a adressing as I wrote, but you have multiple devices definedd do not tell what you use, so it's hard to help, please follow the guidelines I gave you earlier.

**Comment by janiversen** [comment] 2024-12-24 08:22
And just for information I do not think you initialized coils to be true, the default is still set to false.

**Comment by carthoris** [comment] 2024-12-29 17:04
we are using devicev

"devicev": {
"setup": {
"co size": 8,
"di size": 8,
"ir size": 5,
"hr size": 5,
"shared blocks": false,
"type exception": true,
"defaults": {
"value": {
"bits": 0,
"uint16": 0,
"uint32": 0,
"float32": 0.0,
"string": " "
},
"action": {
"bits": null,
"uint16": null,
"uint32": null,
"float32": null,
"string": null
}
}
},
"invalid": [
],
"write": [
[0, 7],
[21, 25]
],
"bits": [
{"addr": [0, 15], "value": 1}
],
"uint16": [
[16, 25]
],
"uint32": [
],
"float32": [
],
"string": [
],
"repeat": [
]
}

**Comment by janiversen** [comment] 2024-12-29 18:21
But value 1 only sets 1 bit and leaves the rest 0.
