### ISSUE TITLE
Async TCP Client does not reconnect

### ISSUE THREAD

**Issue by jvailius** [pymodbus-dev/pymodbus#1635] opened 2023-06-29 08:00 UTC
### Versions

- Python: 3.11.3
- OS: Debian 12
- Pymodbus: 3.3.2 and 3.4.0.dev0
- Modbus Hardware: SENECA R-8AI-8DIDO

### Pymodbus Specific

- Client: tcp - async

### Description
Hi,

after un-plugging and re-plugging the network cable the client does not reconnect to the server.  I have done some debugging and it seems the `self.transport` property is already set to `None` before the `connection_lost` is called and therefore the reconnect task from the `connection_lost` function is never scheduled:  https://github.com/pymodbus-dev/pymodbus/blob/dev/pymodbus/transport/transport.py#L219-L220

I do not propose it as a bug-fix because the underlying issue may be far more complicated but removing the line https://github.com/pymodbus-dev/pymodbus/blob/dev/pymodbus/transport/transport.py#L296 caused the client to properly reconnect (see both logs).

Thank you,
Jan

### Code and Logs

```python
async def run():
    client = AsyncModbusTcpClient(
        host=HOST,
        port=PORT,
        timeout=1,
        retries=3,
        reconnect_delay=1,
        reconnect_delay_max=5
    )
    await client.connect()

    while True:
        try:
            if client.connected:
                await client.read_coils(address=0, count=1, slave=1)
        except Exception as ex:
            print(ex)
        await asyncio.sleep(5)

if __name__ == "__main__":
    asyncio.run(run(), debug=True)
```

After pulling the plug the log stops
```
2023-06-29 09:50:56,062 DEBUG logging:102 Connecting comm
2023-06-29 09:50:56,064 DEBUG logging:102 Connected to comm
2023-06-29 09:50:56,064 DEBUG logging:102 callback_connected called
2023-06-29 09:50:56,065 DEBUG logging:102 send: 0x0 0x1 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:50:56,065 DEBUG logging:102 send: 0x0 0x1 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:50:56,065 DEBUG logging:102 Adding transaction 1
2023-06-29 09:50:56,082 DEBUG logging:102 recv: 0x0 0x1 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0
2023-06-29 09:50:56,082 DEBUG logging:102 recv: 0x0 0x1 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0 addr=None
2023-06-29 09:50:56,082 DEBUG logging:102 Processing: 0x0 0x1 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0
2023-06-29 09:50:56,082 DEBUG logging:102 Factory Response[ReadCoilsResponse': 1]
2023-06-29 09:50:56,082 DEBUG logging:102 Getting transaction 1
2023-06-29 09:51:01,086 DEBUG logging:102 send: 0x0 0x2 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:51:01,087 DEBUG logging:102 send: 0x0 0x2 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:51:01,087 DEBUG logging:102 Adding transaction 2
2023-06-29 09:51:01,102 DEBUG logging:102 recv: 0x0 0x2 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0
2023-06-29 09:51:01,103 DEBUG logging:102 recv: 0x0 0x2 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0 addr=None
2023-06-29 09:51:01,103 DEBUG logging:102 Processing: 0x0 0x2 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0
2023-06-29 09:51:01,103 DEBUG logging:102 Factory Response[ReadCoilsResponse': 1]
2023-06-29 09:51:01,103 DEBUG logging:102 Getting transaction 2
2023-06-29 09:51:06,106 DEBUG logging:102 send: 0x0 0x3 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:51:06,107 DEBUG logging:102 send: 0x0 0x3 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:51:06,107 DEBUG logging:102 Adding transaction 3

```

After removing https://github.com/pymodbus-dev/pymodbus/blob/dev/pymodbus/transport/transport.py#L296
```
2023-06-29 09:26:42,500 DEBUG logging:102 Connecting comm
2023-06-29 09:26:42,503 DEBUG logging:102 Connected to comm
2023-06-29 09:26:42,503 DEBUG logging:102 callback_connected called
2023-06-29 09:26:42,503 DEBUG logging:102 send: 0x0 0x1 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:26:42,503 DEBUG logging:102 send: 0x0 0x1 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:26:42,504 DEBUG logging:102 Adding transaction 1
2023-06-29 09:26:42,521 DEBUG logging:102 recv: 0x0 0x1 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0
2023-06-29 09:26:42,521 DEBUG logging:102 recv: 0x0 0x1 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0 addr=None
2023-06-29 09:26:42,521 DEBUG logging:102 Processing: 0x0 0x1 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0
2023-06-29 09:26:42,521 DEBUG logging:102 Factory Response[ReadCoilsResponse': 1]
2023-06-29 09:26:42,521 DEBUG logging:102 Getting transaction 1
2023-06-29 09:26:47,528 DEBUG logging:102 send: 0x0 0x2 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:26:47,528 DEBUG logging:102 send: 0x0 0x2 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:26:47,529 DEBUG logging:102 Adding transaction 2
2023-06-29 09:26:47,541 DEBUG logging:102 recv: 0x0 0x2 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0
2023-06-29 09:26:47,541 DEBUG logging:102 recv: 0x0 0x2 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0 addr=None
2023-06-29 09:26:47,541 DEBUG logging:102 Processing: 0x0 0x2 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0
2023-06-29 09:26:47,542 DEBUG logging:102 Factory Response[ReadCoilsResponse': 1]
2023-06-29 09:26:47,542 DEBUG logging:102 Getting transaction 2
2023-06-29 09:26:52,548 DEBUG logging:102 send: 0x0 0x3 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:26:52,549 DEBUG logging:102 send: 0x0 0x3 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:26:52,549 DEBUG logging:102 Adding transaction 3
2023-06-29 09:26:52,561 DEBUG logging:102 recv: 0x0 0x3 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0
2023-06-29 09:26:52,561 DEBUG logging:102 recv: 0x0 0x3 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0 addr=None
2023-06-29 09:26:52,561 DEBUG logging:102 Processing: 0x0 0x3 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0
2023-06-29 09:26:52,561 DEBUG logging:102 Factory Response[ReadCoilsResponse': 1]
2023-06-29 09:26:52,561 DEBUG logging:102 Getting transaction 3
2023-06-29 09:26:57,568 DEBUG logging:102 send: 0x0 0x4 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:26:57,568 DEBUG logging:102 send: 0x0 0x4 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:26:57,569 DEBUG logging:102 Adding transaction 4

2023-06-29 09:26:58,572 DEBUG logging:102 Connection lost comm due to None
2023-06-29 09:26:58,573 DEBUG logging:102 Getting transaction 4
2023-06-29 09:26:58,573 DEBUG logging:102 Wait comm 1000 ms before reconnecting.
2023-06-29 09:26:59,575 DEBUG logging:102 Connecting comm
2023-06-29 09:27:00,579 WARNING logging:108 Failed to connect 
2023-06-29 09:27:00,579 DEBUG logging:102 Wait comm 2000 ms before reconnecting.
2023-06-29 09:27:02,582 DEBUG logging:102 Connecting comm
2023-06-29 09:27:03,575 DEBUG logging:102 send: 0x0 0x5 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:27:03,575 DEBUG logging:102 send: 0x0 0x5 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:27:03,575 DEBUG logging:102 Adding transaction 5
2023-06-29 09:27:03,584 WARNING logging:108 Failed to connect 
2023-06-29 09:27:03,585 DEBUG logging:102 Wait comm 4000 ms before reconnecting.

2023-06-29 09:27:07,589 DEBUG logging:102 Connecting comm
2023-06-29 09:27:08,593 WARNING logging:108 Failed to connect 
2023-06-29 09:27:08,593 DEBUG logging:102 Wait comm 5000 ms before reconnecting.
2023-06-29 09:27:09,581 DEBUG logging:102 send: 0x0 0x6 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:27:09,582 DEBUG logging:102 send: 0x0 0x6 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:27:09,582 DEBUG logging:102 Adding transaction 6

2023-06-29 09:27:13,598 DEBUG logging:102 Connecting comm
2023-06-29 09:27:13,601 DEBUG logging:102 Connected to comm
2023-06-29 09:27:13,602 DEBUG logging:102 callback_connected called
2023-06-29 09:27:15,589 DEBUG logging:102 send: 0x0 0x7 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:27:15,589 DEBUG logging:102 send: 0x0 0x7 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-06-29 09:27:15,590 DEBUG logging:102 Adding transaction 7
2023-06-29 09:27:15,607 DEBUG logging:102 recv: 0x0 0x7 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0
2023-06-29 09:27:15,607 DEBUG logging:102 recv: 0x0 0x7 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0 addr=None
2023-06-29 09:27:15,607 DEBUG logging:102 Processing: 0x0 0x7 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0
2023-06-29 09:27:15,608 DEBUG logging:102 Factory Response[ReadCoilsResponse': 1]
```

**Comment by janiversen** [comment] 2023-06-29 10:07
connection_lost starts the reconnect task independent of self.transport,

```
    def connection_lost(self, reason: Exception):
        """Call from asyncio, when the connection is lost or closed.

        :param reason: None or an exception object
        """
        if not self.transport:
            return
        Log.debug("Connection lost {} due to {}", self.comm_params.comm_name, reason)
        self.transport_close()
        if not self.is_server:
            self.reconnect_task = asyncio.create_task(self.do_reconnect())
        self.callback_disconnected(reason)
```
That is if nobody called close().

Furthermore it is strange there are no more entries in the log, might be something is looping forever.

I will do a short test of your assumption.

**Comment by jvailius** [comment] 2023-06-29 10:41
Thanks for the quick response @janiversen,

> Our tests include a test of reconnection (provided reconnect_delay= is set).

We have a test for the async client as well using the Pymodbus server and reconnecting works well. So I was surprised to see that it did not work with actual hardware connected.

Jan

**Comment by janiversen** [comment] 2023-06-29 10:57
Your patch have a number of side-effects.

What happens are, the library to reconnect, but not retry ! It informs that application by raising ConnectionException, so the application can decide to retry the call or not. I cannot tell you, why your except clause do not catch it.

I think you expected a retry, which would be a nice enhancement, but it is dangerous. Think of a write command that steps e.g. a motor, if we automatically retry that command the motor might have problems.

**Comment by jvailius** [comment] 2023-06-29 11:09
> I think you expected a retry, which would be a nice enhancement, but it is dangerous

Sorry if my description might have been confusing: I am wondering why the client does not **reconnect** (not retry) automatically.

**Comment by janiversen** [comment] 2023-06-29 11:12
We are reworking some of the client code, so lets see if we can do something for release 3.4

**Comment by janiversen** [comment] 2023-07-01 10:26
Your example code should get an exception, at least when I try with the newest dev. You need to handle that exception, because it tells you the call did not work out. If you do not handle the exception the program terminates and you never see the reconnect.

**Comment by jvailius** [comment] 2023-07-03 07:39
Thank you @janiversen for the hint.  I will do some more debugging and paste my findings here. It may well be that I have not fully understood how `retry` and `reconnect` are related to each other.

**Comment by jvailius** [comment] 2023-07-04 07:15
Here is a little screencast of the debugging 3.4.0.dev0 after I pulled the plug. The `do_reconnect` task is never scheduled in `connection_lost` because self.transport is already `None`. Is this the expected behavior, do I need to reconnect myself? If so, I wonder what to do with the `reconnect_xxx` settings.

[Screencast from 2023-07-04 09-03-50.webm](https://github.com/pymodbus-dev/pymodbus/assets/132345756/ddc0872d-7676-40c9-ac6b-2ca087ede9f9)

**Comment by janiversen** [comment] 2023-07-04 08:12
I cannot view your screencast. Have a look at our test cases, especially sub_transport, we are testing that the do_reconnect task is scheduled.

You do not need to connect again, but you do need to retry the call.

I will take your code and run it once in our test harness, because I still do not understand why you do not get an error or an exception.

**Comment by jvailius** [comment] 2023-07-04 08:18
> I cannot view your screencast.

Ok - sorry. I thought this is much easier. Strange that you can not see the webm. Indeed I get a `TimeoutError`. I will give it a try with removing `if client.connected`. Thanks for your patience.

**Comment by jvailius** [comment] 2023-07-04 09:43
Thank you @janiversen and apologies for being so suborn, but ...

I also have my own test case for the reconnect (running a Pymodbus server locally) and it works just fine!
But with real hardware over the network it doesn't - there is the confusing part . Here are the logs with the new code tested with pymodbus **3.3.2** and Python **3.11**:

 ```python
async def run():
    client = AsyncModbusTcpClient(
        host="192.168.77.10",
        timeout=1,
        retries=0,
        reconnect_delay=1,
        reconnect_delay_max=1
    )
    await client.connect()

    while True:
        try:
            await client.read_coils(address=0, count=1, slave=1)
        except TimeoutError as err:
            print(datetime.now(), 'TimeoutError', err)
        except Exception as ex:
            print(datetime.now(), 'Exception', ex)
        await asyncio.sleep(5)

if __name__ == "__main__":
    asyncio.run(run(), debug=True)
```

I plugged it off (as you can see in the logs) and plugged it back in after 2023-07-04 11:33:18. Changing retries to e.g. 3 does not change the behavior.

```
2023-07-04 11:32:52,257 DEBUG logging:102 Connecting to 192.168.77.10:502.
2023-07-04 11:32:52,257 DEBUG logging:102 Connecting comm
2023-07-04 11:32:52,260 DEBUG logging:102 Connected to comm
2023-07-04 11:32:52,261 DEBUG logging:102 send: 0x0 0x1 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-07-04 11:32:52,262 DEBUG logging:102 Adding transaction 1
2023-07-04 11:32:52,279 DEBUG logging:102 recv: 0x0 0x1 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0
2023-07-04 11:32:52,279 DEBUG logging:102 recv: 0x0 0x1 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0
2023-07-04 11:32:52,279 DEBUG logging:102 Processing: 0x0 0x1 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0
2023-07-04 11:32:52,279 DEBUG logging:102 Factory Response[ReadCoilsResponse': 1]
2023-07-04 11:32:52,279 DEBUG logging:102 Getting transaction 1
2023-07-04 11:32:57,288 DEBUG logging:102 send: 0x0 0x2 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-07-04 11:32:57,289 DEBUG logging:102 Adding transaction 2
2023-07-04 11:32:57,299 DEBUG logging:102 recv: 0x0 0x2 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0
2023-07-04 11:32:57,300 DEBUG logging:102 recv: 0x0 0x2 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0
2023-07-04 11:32:57,300 DEBUG logging:102 Processing: 0x0 0x2 0x0 0x0 0x0 0x4 0x1 0x1 0x1 0x0
2023-07-04 11:32:57,300 DEBUG logging:102 Factory Response[ReadCoilsResponse': 1]
2023-07-04 11:32:57,300 DEBUG logging:102 Getting transaction 2
2023-07-04 11:33:02,310 DEBUG logging:102 send: 0x0 0x3 0x0 0x0 0x0 0x6 0x1 0x1 0x0 0x0 0x0 0x1
2023-07-04 11:33:02,311 DEBUG logging:102 Adding transaction 3
2023-07-04 11:33:03.319168 TimeoutError 
2023-07-04 11:33:03,320 DEBUG logging:102 Connection lost comm due to None
2023-07-04 11:33:03,320 DEBUG logging:102 Getting transaction 3
2023-07-04 11:33:08.327230 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:33:13.335840 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:33:18.344373 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:33:23.351324 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:33:28.359285 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:33:33.367154 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:33:38.375364 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:33:43.383521 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:33:48.390697 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:33:53.398431 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:33:58.406934 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:34:03.415441 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:34:08.423581 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:34:13.431825 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:34:18.440283 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:34:23.448555 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:34:28.456742 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:34:33.464997 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:34:38.473180 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:34:43.482433 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:34:48.491029 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:34:53.499834 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:34:58.508163 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:35:03.516057 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:35:08.523936 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:35:13.531903 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:35:18.540251 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:35:23.548474 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:35:28.556515 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:35:33.564513 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:35:38.571215 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:35:43.574276 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:35:48.581576 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:35:53.586292 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:35:58.590264 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:36:03.594985 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:36:08.598274 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:36:13.605489 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:36:18.613461 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:36:23.621641 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:36:28.626842 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:36:33.631260 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:36:38.639211 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:36:43.647702 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:36:48.654374 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:36:53.659714 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:36:58.667367 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:37:03.675802 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:37:08.684316 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:37:13.692659 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:37:18.701019 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:37:23.709371 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:37:28.717811 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:37:33.722896 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
2023-07-04 11:37:38.728789 Exception Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.77.10:502]
```

**Comment by janiversen** [comment] 2023-07-04 09:58
Of course.

you are getting a timeout error, before pymodbus receives the e of from the socket library. Timeout needs to be bigger than the time it takes for the socket library to report eof.

**Comment by janiversen** [comment] 2023-07-05 09:54
Closing issue, as this this is not a bug in pymodbus, but wrong usage of timeout.

**Closed by janiversen** 2023-07-05 09:54 UTC
Labels: Enhancements

**Comment by jvailius** [comment] 2023-07-05 10:02
I have played with increasing `timeout` settings but still an automatic reconnect is not triggered. But I have "solved" it by doing a reconnect myself.

**Comment by janiversen** [comment] 2023-07-05 15:23
It reconnects automatically on my raspberry pi 4 (homeassistant, special version), without problems timeout is set to 60 seconds.

Remark if you just unplug the cable, you need to wait for 3 times keepalive (typically 30seconds).

**Comment by jvailius** [comment] 2023-07-06 05:39
> It reconnects automatically on my raspberry pi 4 (homeassistant, special version), without problems timeout is set to 60 seconds.
> 
> Remark if you just unplug the cable, you need to wait for 3 times keepalive (typically 30seconds).

Thank you for the guidance and testing. I will give it a try!
